pipeline {
    agent any 
    environment {
        RELEASE='20.04'
        }
     stages {
        stage('Build') {
            agent any
            environment {
               LOG_LEVEL='INFO'
                }
             steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
                 withCredentials([string(credentialsId: 'ba239e6b-3b6a-432f-9740-9042e32c0f43', variable: 'SLACK_TOKEN')]) {
                   echo "All good"
                }
                }
            }
         stage('Test') {
             steps {
                echo "Testing. I can see release ${RELEASE}"
                writeFile file: 'test-results.txt', text: 'passed'
                }
            }
    }
    post {
        success {
            archiveArtifacts 'test-results.txt'
            slackSend channel: '#jenkins',
            message: 'elease ${env.RELEASE}, success: ${currentBuild.fullDisplayName}.'
        }
    }
}
