pipeline {
  environment {
    imagename = "mydockerimage"
    registryCredential = "ecr:ap-south-1:apurvisri"
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/apurvisri/Docker.git'
      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build imagename + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
            docker.withRegistry('https://*.dkr.ecr.ap-south-1.amazonaws.com', registryCredential) {
            dockerImage.push("$BUILD_NUMBER")
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
            sh "docker rmi -f $imagename:$BUILD_NUMBER"
            sh "docker rmi -f *.dkr.ecr.ap-south-1.amazonaws.com/$imagename:$BUILD_NUMBER"
      }
    }
  }
}
  
